### ISSUE TITLE
Not a issue but...

### ISSUE THREAD

**Issue by OptimusMusmus** [vrabb-gh/animated-items#3]
Would it be possible to make it so that the sword effect is compatible with the following mod: https://modrinth.com/datapack/tool-trims

**Comment by vrabb-gh** [comment]
I've tried and the good thing is that this is possible. However, I'll need to get the mod creator's permission. I'll let you know if they do.

**Comment by vrabb-gh** [comment]
Hey there! I am excited to let you know that the mod creator of Tool Trims has given me permission to animate the textures! It will take some time though, because it's around 160 items. And I'm thinking of giving them all unique animations. But stay tuned for the next update!
