### ISSUE TITLE
Enchanted Diamond Sword is incompatible with Feather Client (Texture breaks)

### ISSUE THREAD

**Issue by ifyouknowyk** [vrabb-gh/animated-items#4]
![image](https://github.com/user-attachments/assets/f8b0a8b0-131d-43bb-a7de-10189b8d4965)

**Comment by vrabb-gh** [comment]
After testing in the latest version, I couldn't find the issue. Could you list your resource packs or mods that you are using?

**Comment by ifyouknowyk** [comment]
yeah here are my mods and enabled packs
![image](https://github.com/user-attachments/assets/03b157f6-5c2e-41ae-ac64-874e83dc17a5)
![image](https://github.com/user-attachments/assets/8d36cb7a-d7fb-4ab8-aa78-c8f95e0f99f0)
![image](https://github.com/user-attachments/assets/01a17fca-066d-40c9-8952-d08909868eeb)
![image](https://github.com/user-attachments/assets/e4dbdfd1-e41b-4ce7-b28c-084117f8b8d4)
![image](https://github.com/user-attachments/assets/0a90ba0b-d8e9-4bb8-9e85-d43aa8447a8c)
![image](https://github.com/user-attachments/assets/4ae3b87c-d719-46ae-a3de-3063e8ad5fc4)
![image](https://github.com/user-attachments/assets/a31abbfa-fade-41a8-9b03-86a2b7e27bb6)

**Comment by vrabb-gh** [comment]
Thank you, I'll go through these mods and resource packs to see which could be breaking the animation. Also, I have a feeling it may be Feather Client, however, I am using a Macbook, which means that I can't test it (Feather Client is only on Windows). So if you could, try to temporarily remove all your mods and test out the resource pack with Feather Client only.

**Comment by ifyouknowyk** [comment]
Ddoing that rn

**Comment by ifyouknowyk** [comment]
yeah its doing it with no resource packs and no mods enabled

**Comment by ifyouknowyk** [comment]
do you know of a fix?

**Comment by vrabb-gh** [comment]
Unfortunately, I cannot fix this issue. However, there is something you can do. You can report this bug to Feather Client saying that item animations don't work, and then you can temporarily switch to Fabric (because all of your mods are compatible with it). At one point, Feather Client should fix the issue, and then you can use it again.
